name: Test runner

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hiển thị thư mục hiện tại
        run: pwd

      - name: Liệt kê file
        run: ls -la

      - name: Kiểm tra Git
        run: git --version

      - name: Kiểm tra Node
        run: node --version

      - name: Kiểm tra .NET
        run: dotnet --version

      - name: Error
        run: abcxyz